# Generated by Django 3.0.8 on 2021-02-14 23:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cliente_cli',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cli', to=settings.AUTH_USER_MODEL),
        ),
    ]
