# Generated by Django 5.2.8 on 2025-12-08 23:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_feedpost_produto_is_available_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img_prod',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
