# Generated by Django 3.0.8 on 2021-02-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20210214_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
