# Generated by Django 5.2.8 on 2025-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_storeconfig_carrinho_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='feed_posts', to='loja.produto', verbose_name='Produtos Vinculados'),
        ),
    ]
