# Generated by Django 5.2.8 on 2025-12-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_feedpost_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='fixed_shipping_price',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Valor cobrado quando não atinge o mínimo para frete grátis.', max_digits=10, verbose_name='Valor fixo do frete'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=300.0, help_text='Compras acima deste valor têm frete grátis. Use 0 para desativar.', max_digits=10, verbose_name='Valor mínimo para frete grátis'),
        ),
    ]
