"""
Django settings for gbstr project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import cloudinary  # cloudinary
import cloudinary.uploader  # cloudinary
import cloudinary.api  # cloudinary
# import psycopg2.extensions
import os

# os.environ.setdefault("DJANGO_SETTINGS_MODULE", __file__)
import django
# import static
from django.conf.global_settings import DATABASES

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'jz91+(t=#6sdlnsykv)b*f#op@-qv1j22=x-xg)hc$q7_8kurc')

#
#
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-guest-id',  # Custom header for guest cart
]

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_ajax',
    # 'pwa',
    'gbstr',
    'loja',
    'cloudinary',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # 'django_pagarme',
    # 'django-heroku'
]
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/'

LOGIN_REDIRECT_URL = '/'

MIDDLEWARE_CLASSES = (

    'whitenoise.middleware.WhiteNoiseMiddleware'
)

# django.setup()

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gbstr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request'
            ],
        },
    },
]

WSGI_APPLICATION = 'gbstr.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
client_encoding = 'UTF8'
timezone = 'America/Sao_Paulo'
default_transaction_isolation = 'read committed'

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'postgres',
    #     'USER': 'postgres',
    #     # 'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '5432'
    # },
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': "db.sqlite3",
    }
}

# import dj_database_url
# DATABASES['default'] = dj_database_url.config(default='postgres://bqutzjqhbzyeun:2a696be3f207322ebfba850995ca6ffd4f658b34664d2240a149803a9b9a4468@ec2-52-4-171-132.compute-1.amazonaws.com:5432/d185ti2fvcrrac')
# DATABASES['default'] = dj_database_url.config()

AUTH_USER_MODEL = "loja.Cliente"

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# django_heroku.settings(locals())

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = ( os.path.join(BASE_DIR, 'loja/static'), )
MEDIA_ROOT = os.path.join(BASE_DIR, '../gblack_store/loja/static/')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, '../gblack_store/loja/')


PWA_APP_NAME = 'GBlack'
PWA_APP_DESCRIPTION = "seu produto esta aqui"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/my_app_icon.png',
        'sizes': '160x160'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/my_apple_icon.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'pt-BR'

cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', "gblack"),
    api_key=os.environ.get('CLOUDINARY_API_KEY', "191418815964556"),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', "hvTxhjD4ZyfYigVrte6ucol0lio")
)

# GERENCIANET
CLIENT_ID_GBLACK = os.environ.get('CLIENT_ID_GBLACK', 'Client_Id_ce88682777180d6ba912e693e0c4be5296d08395')
CLIENT_SECRET_GBLACK = os.environ.get('CLIENT_SECRET_GBLACK', 'Client_Secret_f1394fc97a9f02df1efb12478575dbc861e03ca5')
URL_GBLACK = 'https://pix-h.api.efipay.com.br'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'gblacklojaonline@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'glm14407486')

#twilio
# recover  EC31ZN3FWAFK6E9PDT4FJFPA

TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', 'AC3ae32d970db7bc31f1abdb686754e712')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '4517d120b1d596043c54d78acda11c82')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '+5516994288243')


# Dados para integração com Pagarme
# CHAVE_PAGARME_API_PRIVADA = 'ak_live_8jUYbLG5ojzgs9wisry243ycehrk1g'
# CHAVE_PAGARME_CRIPTOGRAFIA_PUBLICA = 'ek_live_kwLtZhdUxIWxbGGC4cHq7cddKh5T21'
#
# # Para validar telefones no Brasil
# PHONENUMBER_DEFAULT_REGION = 'BR'

# PAYPAL_IDENTITY_TOKEN = 'e2WYMTODkM8DQeoYvI4ODlA9e2ZaMzNHp5i2O64HTCc6TjZ1Bhz0g2UZdEe'
# TKN_PAYPAL = 'e2WYMTODkM8DQeoYvI4ODlA9e2ZaMzNHp5i2O64HTCc6TjZ1Bhz0g2UZdEe'

# =============================================================================
# EXTERNAL INTEGRATIONS
# =============================================================================

# Payment Gateway
# Options: 'mock', 'mercadopago'
PAYMENT_GATEWAY = os.environ.get('PAYMENT_GATEWAY', 'mock')
MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MERCADOPAGO_ACCESS_TOKEN', '')
MERCADOPAGO_PUBLIC_KEY = os.environ.get('MERCADOPAGO_PUBLIC_KEY', '')

# Shipping Provider  
# Options: 'mock', 'melhorenvio'
SHIPPING_PROVIDER = os.environ.get('SHIPPING_PROVIDER', 'mock')
MELHORENVIO_TOKEN = os.environ.get('MELHORENVIO_TOKEN', '')
MELHORENVIO_SANDBOX = os.environ.get('MELHORENVIO_SANDBOX', 'True') == 'True'

# Invoice Provider (NF-e)
# Options: 'mock', 'bling', 'tiny'
INVOICE_PROVIDER = os.environ.get('INVOICE_PROVIDER', 'mock')
BLING_API_KEY = os.environ.get('BLING_API_KEY', '')
TINY_API_TOKEN = os.environ.get('TINY_API_TOKEN', '')

# Marketplaces
ENABLED_MARKETPLACES = os.environ.get('ENABLED_MARKETPLACES', '').split(',') if os.environ.get('ENABLED_MARKETPLACES') else []

# MercadoLivre
MERCADOLIVRE_ACCESS_TOKEN = os.environ.get('MERCADOLIVRE_ACCESS_TOKEN', '')
MERCADOLIVRE_USER_ID = os.environ.get('MERCADOLIVRE_USER_ID', '')

# Magazine Luiza
MAGALU_CLIENT_ID = os.environ.get('MAGALU_CLIENT_ID', '')
MAGALU_CLIENT_SECRET = os.environ.get('MAGALU_CLIENT_SECRET', '')
MAGALU_ACCESS_TOKEN = os.environ.get('MAGALU_ACCESS_TOKEN', '')

# Shopee
SHOPEE_PARTNER_ID = os.environ.get('SHOPEE_PARTNER_ID', '')
SHOPEE_PARTNER_KEY = os.environ.get('SHOPEE_PARTNER_KEY', '')
SHOPEE_SHOP_ID = os.environ.get('SHOPEE_SHOP_ID', '')
SHOPEE_ACCESS_TOKEN = os.environ.get('SHOPEE_ACCESS_TOKEN', '')

# Store Settings (for shipping)
STORE_ZIP_CODE = os.environ.get('STORE_ZIP_CODE', '01310100')  # CEP da loja
STORE_ADDRESS = {
    'name': os.environ.get('STORE_NAME', 'GBlack Store'),
    'phone': os.environ.get('STORE_PHONE', ''),
    'email': os.environ.get('STORE_EMAIL', 'contato@gblack.com.br'),
    'document': os.environ.get('STORE_CNPJ', ''),
    'address': os.environ.get('STORE_ADDRESS', ''),
    'number': os.environ.get('STORE_NUMBER', ''),
    'neighborhood': os.environ.get('STORE_NEIGHBORHOOD', ''),
    'city': os.environ.get('STORE_CITY', 'São Paulo'),
    'state': os.environ.get('STORE_STATE', 'SP'),
    'postal_code': os.environ.get('STORE_ZIP_CODE', '01310100'),
}
