"""
MercadoPago Payment Service Implementation.
https://www.mercadopago.com.br/developers/pt/docs

Requires: pip install mercadopago
"""
import logging
from decimal import Decimal
from datetime import datetime, timedelta
from typing import Optional

from django.conf import settings

from .base import (
    PaymentServiceInterface, 
    PixResponse, 
    CardChargeResponse, 
    BoletoResponse,
    PaymentStatusResponse,
    PaymentStatus
)

logger = logging.getLogger(__name__)


class MercadoPagoService(PaymentServiceInterface):
    """
    MercadoPago integration for PIX, Cards and Boleto.
    
    Required settings:
    - MERCADOPAGO_ACCESS_TOKEN
    - MERCADOPAGO_PUBLIC_KEY (for frontend)
    """
    
    def __init__(self):
        self.access_token = getattr(settings, 'MERCADOPAGO_ACCESS_TOKEN', '')
        self._sdk = None
    
    @property
    def sdk(self):
        """Lazy load MercadoPago SDK"""
        if self._sdk is None:
            try:
                import mercadopago
                self._sdk = mercadopago.SDK(self.access_token)
            except ImportError:
                raise ImportError("mercadopago package not installed. Run: pip install mercadopago")
        return self._sdk
    
    def _map_status(self, mp_status: str) -> PaymentStatus:
        """Map MercadoPago status to our enum"""
        status_map = {
            'pending': PaymentStatus.PENDING,
            'approved': PaymentStatus.APPROVED,
            'authorized': PaymentStatus.APPROVED,
            'in_process': PaymentStatus.PENDING,
            'in_mediation': PaymentStatus.PENDING,
            'rejected': PaymentStatus.REJECTED,
            'cancelled': PaymentStatus.CANCELLED,
            'refunded': PaymentStatus.REFUNDED,
            'charged_back': PaymentStatus.REFUNDED,
        }
        return status_map.get(mp_status, PaymentStatus.PENDING)
    
    def create_pix(self, order_id: int, amount: Decimal,
                   customer_email: str, description: str) -> PixResponse:
        """
        Create PIX payment.
        Returns QR code for customer to scan.
        """
        payment_data = {
            "transaction_amount": float(amount),
            "description": description,
            "payment_method_id": "pix",
            "payer": {
                "email": customer_email
            },
            "external_reference": str(order_id),
        }
        
        result = self.sdk.payment().create(payment_data)
        response = result.get("response", {})
        
        if result.get("status") != 201:
            logger.error(f"MercadoPago PIX error: {response}")
            raise Exception(f"Erro ao criar PIX: {response.get('message', 'Erro desconhecido')}")
        
        pix_data = response.get("point_of_interaction", {}).get("transaction_data", {})
        
        return PixResponse(
            qr_code=pix_data.get("qr_code_base64", ""),
            qr_code_text=pix_data.get("qr_code", ""),
            transaction_id=str(response.get("id")),
            expires_at=datetime.now() + timedelta(minutes=30)
        )
    
    def create_card_charge(self, order_id: int, amount: Decimal,
                          card_token: str, installments: int = 1) -> CardChargeResponse:
        """
        Process credit card payment.
        card_token is generated by MercadoPago.js on frontend.
        """
        payment_data = {
            "transaction_amount": float(amount),
            "token": card_token,
            "installments": installments,
            "payment_method_id": "visa",  # Will be auto-detected from token
            "external_reference": str(order_id),
        }
        
        result = self.sdk.payment().create(payment_data)
        response = result.get("response", {})
        
        status = self._map_status(response.get("status", ""))
        
        return CardChargeResponse(
            transaction_id=str(response.get("id", "")),
            status=status,
            authorization_code=response.get("authorization_code"),
            error_message=response.get("status_detail") if status == PaymentStatus.REJECTED else None
        )
    
    def create_boleto(self, order_id: int, amount: Decimal,
                     customer_data: dict, due_days: int = 3) -> BoletoResponse:
        """
        Generate boleto bancário.
        customer_data: {first_name, last_name, email, cpf, address}
        """
        due_date = datetime.now() + timedelta(days=due_days)
        
        payment_data = {
            "transaction_amount": float(amount),
            "payment_method_id": "bolbradesco",  # Bradesco boleto
            "external_reference": str(order_id),
            "date_of_expiration": due_date.isoformat(),
            "payer": {
                "email": customer_data.get("email"),
                "first_name": customer_data.get("first_name"),
                "last_name": customer_data.get("last_name"),
                "identification": {
                    "type": "CPF",
                    "number": customer_data.get("cpf", "").replace(".", "").replace("-", "")
                },
                "address": customer_data.get("address", {})
            }
        }
        
        result = self.sdk.payment().create(payment_data)
        response = result.get("response", {})
        
        if result.get("status") != 201:
            logger.error(f"MercadoPago Boleto error: {response}")
            raise Exception(f"Erro ao criar boleto: {response.get('message', 'Erro desconhecido')}")
        
        return BoletoResponse(
            barcode=response.get("barcode", {}).get("content", ""),
            digitable_line=response.get("barcode", {}).get("content", ""),
            pdf_url=response.get("transaction_details", {}).get("external_resource_url", ""),
            transaction_id=str(response.get("id")),
            due_date=due_date
        )
    
    def check_payment_status(self, transaction_id: str) -> PaymentStatusResponse:
        """Check payment status by transaction ID"""
        result = self.sdk.payment().get(transaction_id)
        response = result.get("response", {})
        
        status = self._map_status(response.get("status", ""))
        paid_at = None
        
        if status == PaymentStatus.APPROVED:
            date_approved = response.get("date_approved")
            if date_approved:
                paid_at = datetime.fromisoformat(date_approved.replace("Z", "+00:00"))
        
        return PaymentStatusResponse(
            transaction_id=transaction_id,
            status=status,
            paid_at=paid_at,
            amount_paid=Decimal(str(response.get("transaction_amount", 0)))
        )
    
    def refund_payment(self, transaction_id: str,
                       amount: Optional[Decimal] = None) -> bool:
        """Refund a payment (partial or full)"""
        refund_data = {}
        if amount:
            refund_data["amount"] = float(amount)
        
        result = self.sdk.refund().create(transaction_id, refund_data)
        return result.get("status") == 201
    
    def process_webhook(self, payload: dict) -> PaymentStatusResponse:
        """
        Process webhook notification from MercadoPago.
        Called when payment status changes.
        """
        action = payload.get("action")
        data = payload.get("data", {})
        
        if action == "payment.updated" or action == "payment.created":
            payment_id = data.get("id")
            if payment_id:
                return self.check_payment_status(str(payment_id))
        
        raise ValueError(f"Unknown webhook action: {action}")


class MockPaymentService(PaymentServiceInterface):
    """
    Mock payment service for development/testing.
    Always returns successful responses.
    """
    
    def create_pix(self, order_id: int, amount: Decimal,
                   customer_email: str, description: str) -> PixResponse:
        return PixResponse(
            qr_code="MOCK_QR_CODE_BASE64",
            qr_code_text=f"00020126580014br.gov.bcb.pix0136mock-pix-{order_id}",
            transaction_id=f"MOCK-PIX-{order_id}",
            expires_at=datetime.now() + timedelta(minutes=30)
        )
    
    def create_card_charge(self, order_id: int, amount: Decimal,
                          card_token: str, installments: int = 1) -> CardChargeResponse:
        return CardChargeResponse(
            transaction_id=f"MOCK-CARD-{order_id}",
            status=PaymentStatus.APPROVED,
            authorization_code="MOCK123"
        )
    
    def create_boleto(self, order_id: int, amount: Decimal,
                     customer_data: dict, due_days: int = 3) -> BoletoResponse:
        return BoletoResponse(
            barcode="12345.67890 12345.678901 12345.678901 1 12340000010000",
            digitable_line="12345678901234567890123456789012345678901234567",
            pdf_url=f"https://example.com/boleto/{order_id}.pdf",
            transaction_id=f"MOCK-BOLETO-{order_id}",
            due_date=datetime.now() + timedelta(days=due_days)
        )
    
    def check_payment_status(self, transaction_id: str) -> PaymentStatusResponse:
        return PaymentStatusResponse(
            transaction_id=transaction_id,
            status=PaymentStatus.APPROVED,
            paid_at=datetime.now(),
            amount_paid=Decimal("100.00")
        )
    
    def refund_payment(self, transaction_id: str,
                       amount: Optional[Decimal] = None) -> bool:
        return True
    
    def process_webhook(self, payload: dict) -> PaymentStatusResponse:
        return PaymentStatusResponse(
            transaction_id=payload.get("id", "MOCK"),
            status=PaymentStatus.APPROVED,
            paid_at=datetime.now()
        )


def get_payment_service() -> PaymentServiceInterface:
    """
    Factory function to get the configured payment service.
    Uses PAYMENT_GATEWAY setting to determine which implementation.
    """
    gateway = getattr(settings, 'PAYMENT_GATEWAY', 'mock')
    
    if gateway == 'mercadopago':
        return MercadoPagoService()
    else:
        return MockPaymentService()
